# Generated by Django 3.1.4 on 2021-02-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disptach',
            new_name='Order',
        ),
    ]
