# Generated by Django 3.1.4 on 2021-02-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20210226_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
