# Generated by Django 3.1.4 on 2021-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='initiator',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterModelTable(
            name='order',
            table='customer_order',
        ),
    ]
