# Generated by Django 3.1.4 on 2021-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210226_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recievers_phone',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
