# Generated by Django 3.1.4 on 2021-02-26 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210226_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
