# Generated by Django 3.1.4 on 2021-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210226_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='recievers_phone',
            field=models.CharField(max_length=150),
        ),
    ]
