# Generated by Django 3.1.4 on 2021-02-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
