# Generated by Django 3.1.4 on 2021-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('driver_email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('licence_num', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to=None)),
                ('bike_num', models.CharField(max_length=150)),
                ('licence_date', models.DateField()),
                ('insurance_date', models.DateField()),
                ('licence_file', models.FileField(upload_to=None)),
            ],
            options={
                'db_table': 'driver_info',
            },
        ),
    ]
