# Generated by Django 3.1.4 on 2021-02-26 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snappy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='insurance_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='licence_file',
        ),
        migrations.AddField(
            model_name='driver',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bike_num',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licence_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
