# Generated by Django 3.1.4 on 2021-02-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snappy', '0002_auto_20210226_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='licence_date',
        ),
    ]
